name: AutoUpdate
on:
  workflow_call:
    inputs:
      FILE_PATH:
        type: string
        required: true
      REPO:
        type: string
        required: true
    secrets:
      GITHUB_APP_ID:
        required: true
      GITHUB_APP_PRIVATE_KEY:
        required: true
jobs:
  update-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Create cross repo token
      id: cross-repo-creds
      uses: getsentry/action-github-app-token@v2
      with:
        app_id: ${{ secrets.GITHUB_APP_ID }}
        private_key: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}

    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.REPO }}
        path: 'repo'
        ref: main
        token: ${{ steps.cross-repo-creds.outputs.token }}
        
    - name: Generate random number
      id: genrand
      run: echo "RAND_NUMBER=$RANDOM" >> $GITHUB_OUTPUT

    - name: Update File
      id: updateFile
      run: echo "${{ steps.prname.outputs.RAND_NUMBER }}" > pr-target/random.txt
    
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ steps.cross-repo-creds.outputs.token }}
        path: pr-target
        commit-message: Random Update
        committer: GitHub <noreply@github.com>
        author: GitHub Actions <noreply@github.com>
        assignees: ${{ github.actor }}
        branch: random-number-${{ steps.prname.outputs.RAND_NUMBER }}
        base: main
        delete-branch: true
        title: ${{ steps.prname.outputs.RAND_NUMBER }}
        body: 'Update random file content'
        
    - name: Merge
      run: gh pr merge --merge --admin "${{ steps.cpr.outputs.pull-request-number }}"  --repo ${{ inputs.REPO }}
      env:
       GH_TOKEN: ${{ steps.cross-repo-creds.outputs.token }}
       

