name: Deploy
on:
  workflow_dispatch

jobs:
  deploy-development:
    uses: canadyworkshop/workflow-test/.github/workflows/autopr.yml@main
    with:
      FILE_PATH: "dev.txt"
      REPO: "canadyworkshop/pr-target"
    secrets:
      GITHUB_APP_ID: ${{ secrets.AUTO_PR_MERGE_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.AUTO_PR_MERGE_PRIVATE_KEY }}
  
  
