name: squidtest
on:
  workflow_dispatch:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '*/20 * * * *'

jobs:
  curl:
    name: curltest
    runs-on: ubuntu-latest
    steps:
    - name: curlit
      id: curl-it
      run: curl https://squidward.is.jackhenry.com/app#/users/sign-in
